# Generated by Django 3.2.25 on 2025-03-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250313_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='reorder_level',
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
