# Generated by Django 3.2.25 on 2025-03-13 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20250313_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_predefined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('user', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='mealplan',
            unique_together=set(),
        ),
    ]
